cache:
  CACHE_TYPE: simple
jwt:
  SECRET: foo
  EXPIRE_HOURS: 24
app:
  SALT: bar
  ENV: dev
  SECRET: ^753*&FdFS#4D
  HOST: 43.138.62.224
  PORT: 8000
db:
  MYSQL: mysql+mysqlconnector://root:2020010971@mysql:3306/thss
  # MYSQL: sqlite:///dev.db