cache:
  CACHE_TYPE: simple
jwt:
  SECRET: foo
  EXPIRE_HOURS: 24
app:
  SALT: bar
  ENV: dev
  SECRET: ^753*&FdFS#4D
  HOST: 127.0.0.1
  PORT: 5000
db:
  # MYSQL: mysql+mysqlconnector://root:2020010971@mysql:3306/thss
  MYSQL: sqlite:///dev.db