version: "3"
services:
  app:
    container_name: app
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    command: >
      bash -c "gunicorn -w4 -b 0.0.0.0:5000 --log-level=debug manage:app"
    volumes:
      - .:/app/
      - static-volume:/app/app/static
    expose:
      - "5000"
    depends_on:
      - db
    networks:
      - web_network
      - db_network
  db:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - "/home/ubuntu/mysql/:/var/lib/mysql"
    env_file: .env
    expose:
      - "3306"
    restart: always
    environment:
      - MYSQL_DATABASE=thss
      - MYSQL_ROOT_PASSWORD=2020010971
      - CONTAINER-TIMEZONE=Asia/Shanghai
      - TZ=Asia/Shanghai
    networks:
      - db_network
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]
  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - static-volume:/app/static
      - ./nginx:app.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  static-volume:
